### PR TITLE
NetworkDynamics 0.5 compat

### PR DESCRIPTION
**Pull request by hexaeder**
I've started working on the compatibility with ND@0.5. This also removes the need for this [compatibility code in ND.jl](https://github.com/FHell/NetworkDynamics.jl/blob/40ef9ab65d3ff7ee7401ebde2dd3d604e11ac082/src/nd_ODE_Static.jl#L102).

This is WIP, the following things should be adressed
- [ ] tests for experimental nodes fail (i haven't really looked into this yet)
- [ ] Test for `RLLLine` fails: this is an (the only?) `ODELine`. The `coupling` parameter has to be chosen manually (@lindnemi)
- [ ] the coupling type should explicitly defined for all line types (probably `:antisymmetric`)

### CODE REVIEW

**Comment by lindnemi** [comment]
I am not getting any errors on my machine. Could you post the ErrorMessage here? Please note that ND 0.5.1 requires Julia 1.5 or above.

There are way too many "Info" messages though when running the test. Adding the coupling type to the line definitions solves that. For `ODEEdge` use `coupling=:fiducial` (in `construct_edge`). For `StaticEdge` the quick fix would be `coupling=:fiducial` as well (in the line macro), but in order to benefit from the reuse of variables for antisymmetric edges the line macro has to be adjusted. Then all lines that are antisymmetric should benefit from an ~2x speedup

**Comment by lindnemi** [comment]
I the Documentation CI script, Julia 1.4 is requested. that should be changed to 1.5.

**Comment by lindnemi** [comment]
Moving this PR forward will require to change the PD sign convention. At the moment a PD edge consists of two half edges, of which the first describes the current dst -> src, the second src -> dst. The PD sign convention now says: The first half edges has to be multiplied by `-1`, meaning a PD line is:

```
Line
   (dst -> src) * (-1)
   (src -> dst)
```

In order to get rid of that minus again the `total_current` function multiplies another `-` sign.

```
function total_current(e_s, e_d)
    # Keeping with the convention of negative sign for outging current
    current = 0.0im
    for e in e_s
        current -= e[1] + e[2]*im
    end
    for e in e_d
        current += e[3] + e[4]*im
    end
    current
end
```

Since version 0.5 network dynamics doesn't allow the distinction between `e_s` and `e_d` anymore, meaning that we can either only add or subtract all of the edges. Actually we can get their pretty easily by never introducing the (-1) in the first place, then it doesn't have to be removed in `total_current`.

To further complicate things:

ND's default mode is that the user specifies only the interaction dst -> src and that the package does the rest by itself. For PD there exists the compatability option `:fiducial` which lets a user specify both dst -> src and src -> dst flows. However in this case ND assumes just the oposite order of varibales, namely

```
NDedge
    src -> dst
    dst -> src
```

This is probably relatively easy to work around, but has to be kept in mind when harmonizing both packages.

**Comment by lindnemi** [comment]
Tests should pass now. RLLLine needs more tests, though. At the moment the tests just assert that the fixpoint is correct and i am not sure in how far the FP is affected by the index shuffling from ND to PD. Multiplying the PD `-` or not didn't seem to affect the outcome.

@FHell Indeed you provided some code for plotting RLLLine vs. StaticLine. It was commented out. Does this picture make sense to you? 
RLLLine_new_convention

**Comment by lindnemi** [comment]
I put a `test_broken` in the RLLLine test as a reminder. Other than that the changes can be merged and we're ready for a new NDv0.5 compatible release from my point of view. :)

**Comment by SabineAuer** [comment]
@lindnemi: can you create a branch within PowerDynamics for PRs since it would be so much easier for me to look at this branch locally then?

**Comment by hexaeder** [comment]
With the [Github CLI](https://cli.github.com/) you can checkout the PR with `gh pr checkout 143`

**Comment by lindnemi** [comment]
you could also just clone the PR, right? Those are the exact same steps, i would have to take since the PR is from Hans github account not from mine.

**Comment by SabineAuer** [comment]
I find it nicer to handle everything with branches so I do not have to clone a new repository for each PR. @lindnemi : I added you and Hans to the JuliaEnergy group so you are able to create branches from now on :)

**Comment by lindnemi** [comment]
okay, then i'll do that next time :)

**Comment by hexaeder** [comment]
> can you create a branch within PowerDynamics for PRs since it would be so much easier for me to look at this branch locally then?

It is not possible to change the source branch of a PR. Therfore I had to open a new one #147 for the new repo internal branch `nd0.5_compat`.

**Pull request closed without merging**
