### PR TITLE
compat with NetworkDynamics 0.5

### PR DESCRIPTION
**Pull request by hexaeder**
for previous discussion see #143

### CODE REVIEW

**Comment by lindnemi** [comment]
The RLLine plot on previous version of PD looked like this:

baseline_rll_line

The problem is that i am not sure anymore if the old version without oscillations or the new version with oscillations is correct. In this plot the current flowing from the slack node to the swing node is the same as the current flowing back. In the newer plot they differ.

To produce the newer plot i did the same transformations that worked for all staticlines, but here its not so easy because the symmetry in the implementation of RLLine equations is broken. Should it be broken?

I am afraid that the example we are looking at here (Slack +Swing) is maybe too simple to display all relevant effects because of some non-obvious symmetries. @FHell

**Comment by FHell** [comment]
> The RLLine plot on previous version of PD looked like this:
> 
> baseline_rll_line
> 
> The problem is that i am not sure anymore if the old version without oscillations or the new version with oscillations is correct. In this plot the current flowing from the slack node to the swing node is the same as the current flowing back. In the newer plot they differ.
> 
> To produce the newer plot i did the same transformations that worked for all staticlines, but here its not so easy because the symmetry in the implementation of RLLine equations is broken. Should it be broken?
> 
> I am afraid that the example we are looking at here (Slack +Swing) is maybe too simple to display all relevant effects because of some non-obvious symmetries. @FHell

Okay that's not good. My interpretation is that the current at the left end of the line is correct but at the right end of the line is incorrect in the new ND backend. This probably means the sign for the right hand side is handled incorrectly. Because taht end links into a constraint we don't really see the effect of this incorrect current calculation though. Could you try simulating a system with two Swing Nodes rather than a Slack/Swing system?

**Comment by lindnemi** [comment]
I am still not sure the old model is correct. It says: 
```julia
            # the different minus signs are due to the PowerDynamics sign convention for currents
           [...]
            v_left_right = (- Z * i_left_right .- v_left .+ v_right) ./ L
            v_right_left = (- Z * i_right_left .+ v_right .- v_left) ./ L
```
But if you read the code carefully you realize that there are no different minus signs, its just a permutation of variables.

**Comment by lindnemi** [comment]
@FHell  good idea to use the swing equations. I got the old and new versions two return the same results for the slack&swing, but that doesn't hold anymore for the double swing.
new:
twoswings_new
old:
twoswings_old

however i don't understand why we expect a dynamic line to behave like a static line. what's the point of the dynamical simulation if they behave the same?

**Comment by lindnemi** [comment]
I have been working on this for more than two hours now and i need someone who actually understands the physics to look at this.

**Comment by FHell** [comment]
> @FHell good idea to use the swing equations. I got the old and new versions two return the same results for the slack&swing, but that doesn't hold anymore for the double swing.
> new:
> twoswings_new
> old:
> twoswings_old
> 
> however i don't understand why we expect a dynamic line to behave like a static line. what's the point of the dynamical simulation if they behave the same?

They shouldn't be the same, but approximately the same. Static is an approximation of dynamic. We can have a deeper look together.

**Comment by lindnemi** [comment]
Everything regarding the RLLine should work now. I had a thorough look with Frank and we made sure that everything is at least as correct as before ;). We are now formally testing that static and dynamics solution agree up to 0.001.

HOWEVER, a new bug appeared. 
Normally `systemsize` is defined like this, assuming pg has OrderedDicts of nodes and lines
```
@views systemsize(pg::PowerGrid) = sum(map(n -> dimension(n), collect(values(pg.nodes))))
```
In the test script for RLLine this has to be overloaded since edges may now have a dimension as well:
```
dimension(::StaticLine) = 0
systemsize(pg::PowerGrid) =
        sum(map(n -> dimension(n), pg.nodes)) +
        sum(map(n -> dimension(n), pg.lines))
```
Here Frank assumed that nodes and lines are Vectors. This overload throws off the line failure test which is executed afterwards and assume an OrderedDict for nodes.

Using multiple dispatch to circumvent this problem is not possible without further changes, since PowerGrid doesn't have type parameters for its fields. Alternatively one might lift the RLLine definition to the new standard (and change it to support OrderedDicts). Or most simply just execute the RLLine test as the last script in order to not change anything but leave the tests intact.

**Comment by lindnemi** [comment]
The first two options will change core functionality (slightly) and i'm not sure of the implications. Which would be your preferred option @FHell @SabineAuer?

**Comment by antonplietzsch** [comment]
@lindnemi The tests of the CI failed for your commit.

> LoadError: map is not defined on dictionaries

In PowerDynamics there are at the moment two ways to define nodes and lines, with `Arrays` and with `OrderedDicts`. Both ways have to be supported.

**Comment by hexaeder** [comment]
If both options need to be supported the clean solution is probably to add type parameters
```julia
CollType = Union{OrderedDict, Vector}
struct PowerGrid{G, N, L} where {G<:AbstractGraph, N<:CollType, L<:CollType}
    graph:: G
    nodes::N
    lines::L
end
```
and dispatch `systemsize` on `N` and `L`. I think this would not lead to much change elsewhere because it should be allways okay to use `PowerGrid` as before...

**Comment by lindnemi** [comment]
Ahh, i see. It's actually a lot simpler than i thought. `collect(values(Array))` is defined and returns the same array. Thus we don't need any more dispatching.

**Comment by lindnemi** [comment]
We should probably move this definition: 
```julia
dimension(::StaticLine) = 0
systemsize(pg::PowerGrid) =
        sum(map(n -> dimension(n), collect(values(pg.nodes)))) +
        sum(map(n -> dimension(n), collect(values(pg.lines))))
```

from the test folder into `src`. But this could be done in another PR, so if the test now pass i would consider this PR ready for merging.

**Comment by antonplietzsch** [comment]
The problem is now that
```julia
dimension(::StaticLine) = 0
```
is not enough. `StaticLine` is just one specific model for static lines. The tests are now failing because other static line models like `PiModelLine` have no dimension defined.
> LoadError: MethodError: no method matching dimension(::PiModelLine)

**Comment by lindnemi** [comment]
Admittedly this is a strange workflow but i added additional dispatches for the other LineTypes :sweat_smile:

**Review by lindnemi — COMMENTED** [review]
This wont work since RLLine <: AbstractLine

**Comment by antonplietzsch** [comment]
In the definition of `RLLine` you have:
```julia
dimension(::RLLine) = begin
            4
    end
```
So in that case it will dispatch to this method. For all other lines, where no specific method is given, the dimension will be zero.

**Comment by lindnemi** [comment]
i see. great!

**Comment by antonplietzsch** [comment]
Ok. The test for Julia-1.5 on Windows failed. This problem is due to some bug in the IEEE 14-Bus solution tests and unrelated to the changes made in this branch here. See #154

**Comment by lindnemi** [comment]
When will this be merged?

**Review by antonplietzsch — APPROVED** [review]

**Pull request merged**
