### PR TITLE
Addition of Bus and line names

### PR DESCRIPTION
**Pull request by SabineAuer**
In [Issue 86](https://github.com/JuliaEnergy/PowerDynamics.jl/issues/86) the request for adding node and line names was stated. Here, I started with a first draft for doing so.

### CODE REVIEW

**Comment by SabineAuer** [comment]
@luap-pik: I thought we could solve issue86 by using Dicts for nodes and lines. What do you think? We could also work on the Macro but I find this less intuitive.

**Comment by luap-pik** [comment]
OK, so you suggest to change the fields for `nodes`and `lines` to `Dict` ? That's fine for me, but then I would add a constructor for node lists / line lists for backward compatibility. It could created Dict's automatically with default names, e.g. `N1, ..., N9, ...` and `L1, ..., L9, ...`.

**Comment by luap-pik** [comment]
Looks nice! Only thing is that maybe this function should also return Dicts:

https://github.com/JuliaEnergy/PowerDynamics.jl/blob/59f1626d15cb2f1f9e1212bfdcc3b4063ccabf93/src/common/PowerGrid.jl#L36

Otherwise, e.g. a call to `rhs` should error or not?

**Comment by SabineAuer** [comment]
@luap-pik:  added this [test](https://github.com/JuliaEnergy/PowerDynamics.jl/pull/101/files#diff-4251d7848803d3f0223a72260c7c4e00R28) to make sure the rhs-function still works. 
[Here](https://github.com/JuliaEnergy/PowerDynamics.jl/pull/101/files#diff-e6993303c77b94e291caabf5160e2cf4R29) is how the PowerGrid Struct is generated with a dict. The test sript for PowerGridSoluitons also runs through with nodes and lines as dicts. Does that answer your question?

**Comment by luap-pik** [comment]
OK nice, works for me. It seems that you're missing some tests for States.jl such that codecov complains.

One thing came to my mind, namely that Dicts do not preserve the order of elements. Look at the example [here](https://docs.julialang.org/en/v1/base/collections/#Base.Dict).  So it may happen that `collect(values(..))` returns nodes/lines in an order different from the underlying graph.

**Comment by SabineAuer** [comment]
@luap-pik : I do not see what other tests to add for "States.jl". I inserted the equivalent tests for the dicts as were there for lists.
Concerning the dict values: you think that replacing `collect(values(..))` with ` [pg_dict.nodes[bus] for bus in keys(pg_dict.nodes)]` works out or do you have a more elegant solution in mind?

**Comment by luap-pik** [comment]
If you click on it under "Impacted Files" you see some red lines which are not covered during testing, for instance it complains that the following error is not triggered
```julia
    if ~all( 1 .<= ni .<= length(s.grid.nodes)  )
        throw(BoundsError(s, ni))
    end
```

**Comment by luap-pik** [comment]
@SabineAuer check this, maybe and OrderedDict instead of a normal Dict is the solution?

**Comment by SabineAuer** [comment]
@luap-pik : the user would need to create the OrderedDict if we do not want to go into macro programming for this (I would find this kinda overkill). So I think I favor the solution with [pg_dict.nodes[bus] for bus in keys(pg_dict.nodes)]

**Comment by luap-pik** [comment]
But the problem persists:
```julia
julia> g = ["A"=>1, "B"=>2]
2-element Array{Pair{String,Int64},1}:
 "A" => 1
 "B" => 2

julia> a = Dict(g)
Dict{String,Int64} with 2 entries:
  "B" => 2
  "A" => 1

julia> [a[bus] for bus in keys(a)]
2-element Array{Int64,1}:
 2
 1
``` 
It returns `[2, 1]` and not `[1, 2]`.

However, if the user input is not a `Dict` but the generator `g`, we can internally store this as an `OrderedDict(g)` instead of `Dict(g)`. Then users don't need to think about the data structure at all.

**Comment by SabineAuer** [comment]
@luap-pik : I added the OrderedDict. If you approve this now, I would clean this PR up and then after another review merge this PR. :)

**Comment by SabineAuer** [comment]
@luap-pik : I was talking to Jan and he also said the coverage warnings can be ignored since they are minor. Can you add your review then to this PR? :)

**Comment by luap-pik** [comment]
Great work! thank you for the effort, Sabine!

**Comment by SabineAuer** [comment]
@luap-pik : thanks a lot for you contributions and review ;)

**Comment by SabineAuer** [comment]
@luap-pik: you closed the PR without merging into the master ;)

**Pull request merged**
