### PR TITLE
Adding compat helper 

### PR DESCRIPTION
**Pull request by luap-pik**
I added CompatHelper.jl as a github action [](https://github.com/JuliaRegistries/CompatHelper.jl).
It should automatically maintain the entries in the `[compat]` section.

### CODE REVIEW

**Comment by SabineAuer** [comment]
That sounds great. Do you know how it works?

**Comment by luap-pik** [comment]
As far as I understand it runs daily and checks for updates. When it finds one, it changes the Project.toml and creates a PR.

**Comment by lindnemi** [comment]
NetworkDynamics is at version 0.4 since yesterday. At the moment we get https://github.com/JuliaEnergy/PowerDynamics.jl/issues/99 again, but it's just a small fix to the Project.toml. Hopefully Compat helper will do these things automatically from now on.

**Comment by luap-pik** [comment]
@lindnemi Yeah, I hope so. Did you try it out for ND.jl?

**Comment by lindnemi** [comment]
Not yet - we haven't had compat issues so far

**Comment by SabineAuer** [comment]
Ok, I consulted @janlisse for this PR and he said, it is fine to merge this. I just wanted to double check :)

**Pull request merged**
