### PR TITLE
Operationpoint

### PR DESCRIPTION
**Pull request by luap-pik**
This PR addresses #88 
It adds initial condition guesses and the option to use a steady state problem to the operationpoint search.

### CODE REVIEW

**Comment by luap-pik** [comment]
Sorry for the chaos, I didn't checkout from master :facepalm:

**Comment by luap-pik** [comment]
@SabineAuer apparently, some tests fail on julia 1.2 but pass on 1.4
Do you have the julia older version to check it?

**Comment by SabineAuer** [comment]
somehow the operation point test fails with version 1.2
Locally I have Julia version 1.3.1 and here the tests run properly.

The error message for version 1.2 is:
` @ DiffEqBase ~/.julia/packages/DiffEqBase/gQwlE/src/integrator_interface.jl:333

check found operationpoint: Error During Test at /home/travis/build/JuliaEnergy/PowerDynamics.jl/test/operationpoint/operationpoint.jl:74

  Got exception outside of a @test

  OperationPointError("The operation point search did not converge.")

  Stacktrace:

   [1] #_find_operationpoint_steadystate#75(::Base.Iterators.Pairs{Union{},Union{},Tuple{},NamedTuple{(),Tuple{}}}, ::typeof(PowerDynamics._find_operationpoint_steadystate), ::PowerGrid, ::Array{Float64,1}, ::Nothing, ::Float64) at /home/travis/build/JuliaEnergy/PowerDynamics.jl/src/operationpoint/operationpoint.jl:159

   [2] _find_operationpoint_steadystate(::PowerGrid, ::Array{Float64,1}, ::Nothing, ::Float64) at /home/travis/build/JuliaEnergy/PowerDynamics.jl/src/operationpoint/operationpoint.jl:150

   [3] #find_operationpoint#74(::Nothing, ::Float64, ::Symbol, ::Base.Iterators.Pairs{Union{},Union{},Tuple{},NamedTuple{(),Tuple{}}}, ::typeof(find_operationpoint), ::PowerGrid, ::Nothing) at /home/travis/build/JuliaEnergy/PowerDynamics.jl/src/operationpoint/operationpoint.jl:143

   [4] (::getfield(PowerDynamics, Symbol("#kw##find_operationpoint")))(::NamedTuple{(:sol_method,),Tuple{Symbol}}, ::typeof(find_operationpoint), ::PowerGrid, ::Nothing) at ./none:0 (repeats 2 times)

   [5] top-level scope at /home/travis/build/JuliaEnergy/PowerDynamics.jl/test/operationpoint/operationpoint.jl:100

   [6] top-level scope at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.2/Test/src/Test.jl:1113

   [7] top-level scope at /home/travis/build/JuliaEnergy/PowerDynamics.jl/test/operationpoint/operationpoint.jl:77

   [8] include(::Module, ::String) at ./boot.jl:328

   [9] include_relative(::Module, ::String) at ./loading.jl:1094

   [10] include(::Module, ::String) at ./Base.jl:31

   [11] include(::String) at ./client.jl:431

   [12] top-level scope at util.jl:213

   [13] top-level scope at /home/travis/build/JuliaEnergy/PowerDynamics.jl/test/runtests.jl:35

   [14] top-level scope at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.2/Test/src/Test.jl:1186

   [15] top-level scope at /home/travis/build/JuliaEnergy/PowerDynamics.jl/test/runtests.jl:34

   [16] top-level scope at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.2/Test/src/Test.jl:1113

   [17] top-level scope at /home/travis/build/JuliaEnergy/PowerDynamics.jl/test/runtests.jl:34

   [18] include at ./boot.jl:328 [inlined]

   [19] include_relative(::Module, ::String) at ./loading.jl:1094

   [20] include(::Module, ::String) at ./Base.jl:31

   [21] include(::String) at ./client.jl:431

   [22] top-level scope at none:5

   [23] eval(::Module, ::Any) at ./boot.jl:330

   [24] exec_options(::Base.JLOptions) at ./client.jl:271

   [25] _start() at ./client.jl:464`

**Comment by SabineAuer** [comment]
In installed Julia1.2 locally I got a more detailed error message. Basically the solution somehow does not converge:

check found operationpoint: Test Failed at /home/sabine/JuliaProjects/PowerDynamics.jl/test/operationpoint/operationpoint.jl:88
  Expression: op[:, :i] |> sum == 0.0
   Evaluated: -2.220446049250313e-16 + 0.0im == 0.0
Stacktrace:
 [1] top-level scope at /home/sabine/JuliaProjects/PowerDynamics.jl/test/operationpoint/operationpoint.jl:88
 [2] top-level scope at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.2/Test/src/Test.jl:1113
 [3] top-level scope at /home/sabine/JuliaProjects/PowerDynamics.jl/test/operationpoint/operationpoint.jl:77
┌ Warning: dt <= dtmin. Aborting. There is either an error in your model specification or the true solution is unstable.
└ @ DiffEqBase ~/.julia/packages/DiffEqBase/gQwlE/src/integrator_interface.jl:333
check found operationpoint: Error During Test at /home/sabine/JuliaProjects/PowerDynamics.jl/test/operationpoint/operationpoint.jl:74
  Got exception outside of a @test
  OperationPointError("The operation point search did not converge.")
  Stacktrace:
   [1] #_find_operationpoint_steadystate#75(::Base.Iterators.Pairs{Union{},Union{},Tuple{},NamedTuple{(),Tuple{}}}, ::typeof(PowerDynamics._find_operationpoint_steadystate), ::PowerGrid, ::Array{Float64,1}, ::Nothing, ::Float64) at /home/sabine/JuliaProjects/PowerDynamics.jl/src/operationpoint/operationpoint.jl:159
   [2] _find_operationpoint_steadystate(::PowerGrid, ::Array{Float64,1}, ::Nothing, ::Float64) at /home/sabine/JuliaProjects/PowerDynamics.jl/src/operationpoint/operationpoint.jl:150
   [3] #find_operationpoint#74(::Nothing, ::Float64, ::Symbol, ::Base.Iterators.Pairs{Union{},Union{},Tuple{},NamedTuple{(),Tuple{}}}, ::typeof(find_operationpoint), ::PowerGrid, ::Nothing) at /home/sabine/JuliaProjects/PowerDynamics.jl/src/operationpoint/operationpoint.jl:143
   [4] #find_operationpoint at ./none:0 [inlined] (repeats 2 times)
   [5] top-level scope at /home/sabine/JuliaProjects/PowerDynamics.jl/test/operationpoint/operationpoint.jl:100
   [6] top-level scope at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.2/Test/src/Test.jl:1113
   [7] top-level scope at /home/sabine/JuliaProjects/PowerDynamics.jl/test/operationpoint/operationpoint.jl:77
   [8] include at ./boot.jl:328 [inlined]
   [9] include_relative(::Module, ::String) at ./loading.jl:1094
   [10] include(::Module, ::String) at ./Base.jl:31
   [11] include(::String) at ./client.jl:431
   [12] top-level scope at util.jl:213
   [13] top-level scope at /home/sabine/JuliaProjects/PowerDynamics.jl/test/runtests.jl:35
   [14] top-level scope at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.2/Test/src/Test.jl:1186
   [15] top-level scope at /home/sabine/JuliaProjects/PowerDynamics.jl/test/runtests.jl:34
   [16] top-level scope at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.2/Test/src/Test.jl:1113
   [17] top-level scope at /home/sabine/JuliaProjects/PowerDynamics.jl/test/runtests.jl:34
   [18] include at ./boot.jl:328 [inlined]
   [19] include_relative(::Module, ::String) at ./loading.jl:1094
   [20] include(::Module, ::String) at ./Base.jl:31
   [21] include(::String) at ./client.jl:431
   [22] top-level scope at none:5
   [23] eval(::Module, ::Any) at ./boot.jl:330
   [24] exec_options(::Base.JLOptions) at ./client.jl:271
   [25] _start() at ./client.jl:464

**Comment by luap-pik** [comment]
current state of affairs

Bildschirmfoto zu 2020-06-18 19-18-34

**Comment by luap-pik** [comment]
I added a fallback to nlsolve in case the steady state solution fails. 

Now all tests pass in julia 1.2, 1.3 and 1.4 . :smile: 

Julia 1.0 already fails at installing the packages ...

**Comment by luap-pik** [comment]
@SabineAuer this can be merged now, checks are passing now

**Pull request merged**
