### PR TITLE
Integration of BlockSystems.jl

### PR DESCRIPTION
**Pull request by hexaeder**
I thought it might be a good idea to create a WIP PR for this branch to track progress.

As discussed yesterday, I've added a `IOComponents.jl` module in the `Nodes` directory. The definition of the `GFI_MTK` node is updated to use the new components. I've also removed the tests from the example to the actual node tests.

I added some features to `BlockSystems.jl`. Please make sure to update this package. I'll tag a new version soon so it should not be necessary to install the package directly from github.

### CODE REVIEW

**Comment by hexaeder** [comment]
I've added a first implementation for the NREL generator model in `src/nodes/experimental/MetaGenerator.jl`.
I also defined the most simple version of each component (machine, controler, shaft and prime mover) in `MetaGenerator_example.jl` and plugged it together. It does something.

I've defined the interface in such way, that the machines take the current as input and output a voltage. I'm not totally sure whether this is allways the case for the more complex models...

**Comment by hexaeder** [comment]
I've started implementing the [component library](https://github.com/JuliaEnergy/PowerDynamics.jl/tree/MTK/src/nodes/experimental/MetaGenerator) and added an example how to create an `IONode` based on the `PowerSystems` data structure: 
https://github.com/JuliaEnergy/PowerDynamics.jl/blob/1689c986cc926230c9d21465887f7de4b85f683d/examples/OMIB_PowerSystems/omib.jl#L1-L10

However I've stumbled across a few new questions:
- Whats the `Ωb` parameter which is used in the [Single Mass Shaft](https://nrel-siip.github.io/PowerSimulationsDynamics.jl/stable/component_models/shafts/#Rotor-Mass-Shaft-[SingleMass]) and also some machines? (maybe @jd-lara and @rodrigomha can help with this one)
- We need to figure out how to add a [PSS](https://nrel-siip.github.io/PowerSimulationsDynamics.jl/stable/component_models/pss/) which sits between AVR and machine in our model.
- We need to figure out how to make generator-global parameters, i.e. `ω_ref`, accessible from inside the models. Are there even more parameters like this?

**Comment by antonplietzsch** [comment]
`Ωb` is a base synchronous frequency (e.g. 314.16 rad/s at 50 Hz). So basically this is a per unit system for the frequency (the synchronous frequency then equals 1 pu). In PD we always calculate frequencies in Hz so far.

**Comment by antonplietzsch** [comment]
I think we have to implement the excitation circuit in the [meta generator model](https://nrel-siip.github.io/PowerSimulationsDynamics.jl/stable/models/) as two separate blocks in our BlockSystems structure: an AVR block and an PSS block (so we also need an additional PSS component file in the component library). As you already said, the PSS sits between AVR and machine and adds an additional voltage signal `𝑣_𝑠`. If we have a model without PSS, then `𝑣_𝑠 = 0`.

**Comment by hexaeder** [comment]
I've updated the `MetaGenerator` to support the PSS block. Along with this there where some changes in the internal structure. There are no hardcoded connections anymore. Every variable which is exposed to other systems (i.e. the `outputs` and the `inputs` of each component) need to be unique. The `MetaGenerator` will just connect everything with matching names.

This is was kinda necessary because the AVR/PSS might need to know a lot of different variables. I've choosen the automatic approach over hardcoding more and more links. This means the `MetaGenerator` is also more "hackable" while staying compatible with PowerModels. For example I could create a custom machine with the output `temperature`. If the AVR/PSS has an input called `temperature` those will be connected.

Something I couldn't quite figure out yet is the handling of the parameters. For example the [Simple PSS](https://nrel-siip.github.io/PowerSimulationsDynamics.jl/stable/component_models/pss/) need to know the reference Power `P_ref` which is an internal parameter of the mover. Stuff like this is hard to model in a systematic way with the current BlockSystems.

I might have to go back and add more functionality to BlockSystems. Stuff like 
- convert an open input of a system to an internal parameter
- link several internal parameters (i.e. make them equal)
- maybe allow connections from internal parameter of block A to input of block B?
- maybe allow connections from output of block A to internal parameter of block B?

**Comment by hexaeder** [comment]
Some thougths on the device structure in PowerSystems and how to map them to PowerDynamics. PowerSystems defines the following components of a system, each component class can be accessed via `get_components(Type{<:Component}, system)`.

### Topological elements
They fall in the following typetree:
```
Topology
├─ AggregationTopology
│  ├─ Area
│  └─ LoadZone
├─ Arc
└─ Bus
```
I think we don't need to care to much about those. I guess LoadZones are and Areas are more relevant for time series analysis and stuff. I'd just get the network topology from the Bus and Arc objects.

### Devices
#### Branch 
```
  ACBranch
    ├─ DynamicBranch
    ├─ Line
    ├─ MonitoredLine
    ├─ PhaseShiftingTransformer
    ├─ TapTransformer
    └─ Transformer2W

  DCBranch
    ├─ HVDCLine
    └─ VSCDCLine
```
It is possible, that multiple lines/branches connect the same nodes. I think we should collect all Branch objects per Arc and define special constructors to map them to PD elements, i.e.
```julia
get_pd_branch(Vector{Line}) :: PiModelLine
get_pd_Branch(Vector{TapTransformer}) :: Transformer
get_pd_Branch(Vector{Transformer2W}) :: Transformer
```
I guess we can ignore the `DCBranch`es for now.

#### StaticInjection
I think wie can mostly ignore thos elements. The one we're interest in are the `ElectricLoad`s. For each load we need to define constructors such as
```julia
get_io_load(l::PowerLoad) :: IOBlock
```
which return an `IOBlock` compatible with the `BusNode` interface (voltage in, current out). I hope we can ignore the Generators/Source/Storage all together. I think they are important for the power flow problem but should appear again in the dynamic injections for the dynamic case

```
StaticInjection
    ├─ ElectricLoad
    │  ├─ FixedAdmittance
    │  ├─ ControllableLoad
    │  │  └─ InterruptibleLoad
    │  └─ StaticLoad
    │     └─ PowerLoad
    ├─ Generator
    │  ├─ HydroGen
    │  │  ├─ HydroDispatch
    │  │  ├─ HydroEnergyReservoir
    │  │  └─ HydroPumpedStorage
    │  ├─ RenewableGen
    │  │  ├─ RenewableDispatch
    │  │  └─ RenewableFix
    │  └─ ThermalGen
    │     ├─ ThermalMultiStart
    │     └─ ThermalStandard
    ├─ Source
    ├─ StaticInjectionSubsystem
    │  └─ HybridSystem
    └─ Storage
       ├─ BatteryEMS
       └─ GenericBattery
```

#### DynamicInjection
For dynamic injection we need to define constructors such as
```julia
get_io_injector(inj::DynamicGenerator) :: IOBlock
get_io_injector(inj::DynamicInverter) :: IOBlock
```
```
DynamicInjection
  ├─ DynamicGenerator
  ├─ DynamicInverter
  └─ PeriodicVariableSource
RegulationDevice
```

### PD model construction
If we have set up this constructor structure we can go through all the components. All branches which are associated with a single Arc get transformed into a PD Branche. For each Node we set up a `BusNode` which can take several `IOBlocks` of the form voltage in current out. So for each bus we need to collect all `ElectricLoads` and `DynamicGenerators`, to generate the `BusNode`.

**Comment by hexaeder** [comment]
FYI i've restructured some of the code. Everything NREL related is now in the directory `PowerDynamicsNREL` which itself is a (unregistered) Julia package (probably not the final name). I think we don't want to depend PD on all those NREL packages... and the split will only get more complicated with more and more code.

At some point we should also discuss whether the `IONode` stuff should live inside PD. MTK is a huge dependency..

**Comment by hexaeder** [comment]
further updates:
## the good news
- the OMIB kinda works how i'd expect it
```julia
# load the raw data
raw_file = joinpath(@__DIR__, "OMIB.raw")
dyr_file = joinpath(@__DIR__, "OMIB.dyr")
omib_sys = System(raw_file, dyr_file, runchecks = true) # read system

time_span = (0.0, 30.0)
perturbation_trip = PSID.BranchTrip(1.0, "BUS 1-BUS 2-i_1")

# set up PSD simulation, this also runs the initialisation routine
sim = PSID.Simulation(PSID.ImplicitModel, omib_sys, pwd(), time_span, perturbation_trip)

# we piggyback on the initialisation routine of powersystems
# first we generate an equivalent PowerGrid from the system
# we load `sim.sys` instead of `omib_sys` because it contains initialized machine parameters
pg = PowerGrid(sim.sys);

# we can get the initial condition / operation point from the initialized sim object as well
ic = PSID.get_initial_conditions(sim)
x0 = convert_initial_conditions(pg, sim.sys, ic)

fault = PartialLineFailure("BUS 1 -> BUS 2", 0.5, (1.0, time_span[2]))
sol = simulate(fault, pg, x0, time_span; dtmax=0.01, initializealg=BrownFullBasicInit());
```
OMIB_RotorAngleOMIB_VoltageAngleOMIB_VoltageMagnitude

## the not so good news
- as seen in the first OMIB picture we have a problem with the initialisation at the discontinuity. According to [the DiffEqDocs](https://diffeq.sciml.ai/stable/solvers/dae_solve/#Initialization-Schemes) the used initialisation scheme should not introduce jumps to the differential variables. But it does...
- PS/PSD uses a bus-local base voltage. As soon as we have a system containing several voltage levels this implies that we have to be really carful with the units of line parameters such as transformation ratio, Y, shunts and so forth.
- More of a meta thingi: the whole compatibility layer gets more and more complicated. We should talk again about the actual goals here... otherwise we might end up with a blackbox pipeline from PSSE to PowerDyanmics where a lot of actual modeling decisions happen implicitly deep inside PowerSystems and our compatibility layer.

**Comment by hexaeder** [comment]
- [ ] move all MTK related files to `IONodes` directory
- [ ] create new utils file in this directory
- [ ] move teste (GFI_MTK_Test) to `test/IONodes`, maybe add a solve command to that
- [ ] new test for `BusNode`
- [ ] meaningful examples in `examples` directory (`Literate.jl`)
- [ ] add page to docs which includes the relevant docstrings

**Comment by hexaeder** [comment]
I merged Annas PR into this branch because it added some warnings to the operationpoint search. However the errors in 1.7 are not as trivial to fix as I hoped....

**Review by SabineAuer — APPROVED** [review]

**Pull request merged**
